apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: redcross1-
resources:
- frontend.yaml
- vs-frontend.yaml

# configurations:
# - kustomizeconfig/var_references.yaml


# replacements:
# - source: 
#     name: frontend-service
#     kind: Service
#     version: v1
#   targets:
#   - select: 
#       kind: VirtualService
#       name: frontend-vs
#     fieldPaths:
#     # - spec.hosts
#     - spec.http.0.route.0.destination.host

# vars:
# - name: MY_SERVICE_NAME
#   objref:
#     kind: Service
#     name: frontend-service
#     apiVersion: v1
#   fieldref:
#      fieldpath: metadata.name
